server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: "currencySystem"
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/27-01-changelog.sql
    enabled: true
