name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t currency-tracker:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag currency-tracker:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/currency-tracker:latest
          docker tag currency-tracker:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/currency-tracker:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/currency-tracker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/currency-tracker:${{ github.sha }}